# Nodejs software
language: node_js

node_js:
  - 5.8.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
code_climate:
    repo_token: 67f8f00d5cf9e5c46b7644aebee5ac9df9d6ee267014a6f61a7a7b1048357a1c

sudo: false

# Unit Tests (+code coverage)
script: npm run-script test-travis

after_success:
  # Send coverage data to Coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -Rf ./coverage

before_deploy:
  # Download & embed Nodejs binary
  - NVER=`node -v`
  - wget http://nodejs.org/dist/${NVER}/node-${NVER}-linux-x64.tar.gz
  - tar xzf node-${NVER}-linux-x64.tar.gz
  - mv node-${NVER}-linux-x64 node
  - rm node-${NVER}-linux-x64.tar.gz
  # Clean testing packages
  - npm prune --production
  - tar czf ../ucoin-x64.tar.gz ./ --exclude ".git" --exclude "coverage" --exclude "test"  --exclude "share"

# Releases deployed on GitHub
deploy:
  provider: releases
#  prerelease: true
  skip_cleanup: true
  api_key:
    secure: feyz5YmzYj6g6ZJKAv7u3pp9j9OY6oL4Pcx8mkha25BT1kEIu7lzvkZu4mJAIDjCxJjEkce3fNGXhRICqoMhRy/FK5dUUTpmP3KoMLNNJboO+MhDqjPEb6OYyafikSWnm0BszPL38FzSYMdmvNZ6WirOyVfrdzVPgU6MG0D99w8=
  file:
    - ../ucoin-x64.tar.gz
  on:
    repo: ucoin-io/ucoin
    tags: true
