# Nodejs software
language: node_js

node_js:
  - 5.9.1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
code_climate:
    repo_token: 67f8f00d5cf9e5c46b7644aebee5ac9df9d6ee267014a6f61a7a7b1048357a1c

sudo: false

# Unit Tests (+code coverage)
script: npm run-script test-travis

after_success:
  # Send coverage data to Coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -Rf ./coverage

before_deploy:
  # Download & embed Nodejs binary
  - NVER=`node -v`
  - DUNITER_VER=`git describe --exact-match --tags $(git log -n1 --pretty='%h') | grep -Po "\d.*"`
  - DUNITER_DEB_VER=" $DUNITER_VER"
  - wget http://nodejs.org/dist/${NVER}/node-${NVER}-linux-x64.tar.gz
  - tar xzf node-${NVER}-linux-x64.tar.gz
  - mv node-${NVER}-linux-x64 node
  - rm node-${NVER}-linux-x64.tar.gz
  # Clean testing packages
  - npm prune --production
  - tar czf ../ucoin-x64.tar.gz ./ --exclude ".git" --exclude "coverage" --exclude "test"
  - SRC=`pwd`
  - cd ..
  # GUI Version
  - mkdir ucoin_release
  - NW_RELEASE="v0.14.5"
  - NW="nwjs-${NW_RELEASE}-linux-x64"
  - NW_GZ="${NW}.tar.gz"
  - wget http://dl.nwjs.io/${NW_RELEASE}/${NW_GZ}
  - tar xvzf ${NW_GZ}
  - mv ${NW} ucoin_release/nw
  - cp ${SRC}/gui/* ucoin_release/nw/
  - cp -R ${SRC}/ ucoin_release/sources/
  - rm -Rf ucoin_release/sources/ui/package/node_modules
  - rm -Rf ucoin_release/sources/ui/package/bower_components
  - cd ucoin_release
  - tar czf ../duniter-x64.tar.gz * --exclude ".git" --exclude "coverage" --exclude "test"
  - cd ..
  - mv ucoin_release/sources/ci/travis/debian duniter-x64
  - mkdir -p duniter-x64/opt/duniter/
  - chmod 755 duniter-x64/DEBIAN/post*
  - chmod 755 duniter-x64/DEBIAN/pre*
  - sed -i "s/Version:.*/Version:$DUNITER_DEB_VER/g" duniter-x64/DEBIAN/control
  - cd ucoin_release/sources
  - rm -Rf .git
  - zip -qr ../duniter-desktop.nw *
  - cd ../nw
  - zip -qr ../nw.nwb *
  - cd ../..
  - mv ucoin_release/duniter-desktop.nw duniter-x64/opt/duniter/
  - mv ucoin_release/nw.nwb duniter-x64/opt/duniter/
  - fakeroot dpkg-deb --build duniter-x64
  - mv duniter-x64.deb duniter-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.deb
  - mv duniter-x64.tar.gz duniter-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz
deploy:
  - provider: releases
    prerelease: true
    skip_cleanup: true
    api-key:
      secure: h+GgYhh8/I/l5EWdI1+bDQYtN57jvDf0xhiwcxlfm/AvaJWOZa+q81HsXdHqtwgmsCoRklKtOqTM/nqgSOcWPXsAditRjEXOui2FjZiJCosDjDPMnN6HKzw6XVLtSOx7CeCX/xFmoNTIdsAuC+HUfDWCUFgrsMj9F0V9J3U1nDs=
    file:
    - ucoin-x64.tar.gz
    - duniter-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.deb
    - duniter-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x64.tar.gz
    on:
      repo: duniter/duniter
      tags: true
  - provider: npm
    email: cem.moreau@gmail.com
    api_key:
      secure: gZV7yLxDwwxD4oQXl1hwugmtnWXqP8vojuVGtAGwtMlwJE0n270w6O5xZHDd7DSmOZLftk6/wue/RdhLDsD6J1z3Uxu+VoUWy7aG/sFcGRaBwct+bGqFGkyd+I1mCXFnAZMDwbtgdkQlOCS9PM1BfMEYq49XXqaLaDnwouR+2bI=
    on:
      tags: true
      repo: duniter/duniter
